# File:        Makefile
# Author:      Subhajit Roy  
#              subhajitroy005@gmail.com 

# Moudle:      Drivers  
# Info:        Prepare objects for driver files based 
#              on Selected Platfors             
# Dependency:  None

# This file is part of Re-BOOT Project.

# Re-BOOT is free software: you can redistribute it and/or 
# modify it under the terms of the GNU General Public License 
# as published by the Free Software Foundation, either version 
# 3 of the License, or (at your option) any later version.

# Re-BOOT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License 
# along with Re-BOOT. If not, see <https://www.gnu.org/licenses/>.



##############################################################

obj-y += driver/drv_file_write.o
obj-y += driver/drv_serial.o
obj-y += driver/drv_tcp.o